### ISSUE TITLE
Problem with running the examples behind PROXY

### ISSUE THREAD

**Issue by Doogiemuc** [aws/aws-iot-device-sdk-js#10]
Hello AWS Team!
I am trying to walk through the AWS IoT examples. But I am stuck:
I got the CLI running on my linux machine:
```
ubuntu@linux-server:~/aws-iot-device-sdk$ aws iot list-things
{
    "things": [
        {
            "attributes": {
                "VIN": "4711_EU_Ireland_Dummy_VIN"
            },
            "thingName": "Vehicle-EU-Ireland"
        }
    ]
}
```
But when I try to run the `device-example.js` it seems that it cannot connect:
```
ubuntu@linux-server:~/aws-iot-device-sdk$ nodejs examples/device-example.js -F ./certs.json --test-mode=1
error { [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }
offline
close
reconnect
error { [Error: getaddrinfo ENOTFOUND] code: 'ENOTFOUND', errno: 'ENOTFOUND', syscall: 'getaddrinfo' }
offline
close
```
I am behind a corporate proxy. All settings for that are configured:
* all certificats and private keys are configured in certs.json
* environment variables HTTP_PROXY and HTTP PROXY are set correctly
* I did set the node proxy with `npm config set proxy http://user:pass@proxy.domain.tld:port`   and the same for parameter `https-proxy`
* And i also configured the AWS-SDK for proxy as described in the [AWS-SDK docs](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html#Configuring_a_Proxy)

What else did I miss?

**Comment by Auxolust** [comment]
Hi Doogiemuc, I may be able to help, does your proxy allow traffic through ports 1883 and 8883? These are required by MQTT that this sdk uses, it may be your problem?

**Comment by gkwicker** [comment]
Hi Robert, 

The corporate proxy may be preventing the example programs from reaching the AWS IoT platform. The device SDK uses MQTT exclusively, so access to port 8883 is required. Since it's not using HTTP to connect, the HTTP proxy settings will not have any effect. To rule out a firewall issue on your network can you please try one of the following: 

1. From your Linux machine try a simple telnet command to the service hostname and port 
host$> telnet A3KWJPB3HDC1EC.iot.us-east-1.amazonaws.com 8883 
Trying 54.236.141.103... 
Connected to iotmoonraker-u-elb-1bkszq0bvnbyv-1001897703.us-east-1.elb.amazonaws.com. 
Escape character is '^]'. 

Connection closed by foreign host. 
host$> 

The above shows a successful TCP connection, with the connection eventually being closed due to failed authentication. This would indicate connections on port 8883 are not being blocked. Below shows the same command when attempting on a blocked port: 

host$> telnet <YOUR_HOSTNAME>.iot.us-east-1.amazonaws.com 8883 
Trying 54.236.141.103... 
telnet: connect to address 54.236.141.103: Connection refused 

You may also see a timeout condition:

telnet: Unable to connect to remote host: Connection timed out

2. Try connecting using the SDK from a different network (e.g. a home network or guest network). 

3. Verify publish and subscribe operations with AWS IoT using Eclipse Mosquitto and your certificate/private key as discussed here: 

http://docs.aws.amazon.com/iot/latest/developerguide/verify-pub-sub.html 

We are interested in seeing the results from your tests.

**Comment by gkwicker** [comment]
Hi Robert,

We haven't heard back from you on this issue, so we're assuming it has been resolved.  We're going to close the issue, but please re-open it if you're still having the same problem or have more questions on this topic.

**Comment by bhargav01** [comment]
I have the same issue.
Below is the telnet response,
```
$ > telnet A3KWJPB3HDC1EC.iot.us-east-1.amazonaws.com 8883
Trying 223.255.255.255...
telnet: Unable to connect to remote host: Connection timed out

```

Also the AWSiOT SDK works properly if proxy is not involved.
Is there any config changes available for AWS iot. Like how the aws-sdk has config.update(),
```
aws.config.update({
   httpOptions: { agent: proxy('proxy url') }
});
```

**Comment by bhargav01** [comment]
I have the same issue.
Below is the telnet response,

```
$ > telnet A3KWJPB3HDC1EC.iot.us-east-1.amazonaws.com 8883
Trying <ip that is not 54 series>...
telnet: Unable to connect to remote host: Connection timed out

```
Also the AWSiOT SDK works properly if proxy is not involved.
Is there any config changes available for AWS iot. Like how the aws-sdk has config.update(),

```
aws.config.update({
   httpOptions: { agent: proxy('proxy url') }
});
```
