### ISSUE TITLE
Any way to only get delta from shadow when reconnect?

### ISSUE THREAD

**Issue by wjy617** [aws/aws-iot-device-sdk-js#100]
During thingShadow unconnected, no delta event will be received. When thingShadow reconnected, the iot shadow will have a "delta" field there, is there any way to only get delta, just like listening to delta event? 

Thanks

**Comment by fengsongAWS** [comment]
Hi @wjy617 ,

Thanks for your interest in AWS IoT Node.js SDK. 
Could you elaborate more on your issue?
From what I see here, thing shadows could always listen on delta events whenever there's an update on shadow and difference between desired and reported states.  If the thingShadow reconnected and listen to delta events, and if there is an delta events coming in, your thingShadow should be able to catch that.

Thanks,
Fengyi

Thanks,
Fengyi

**Comment by rpcme** [comment]
I'm pretty sure @wjy617 simply wants ln 235-237 from https://github.com/aws/aws-iot-device-sdk-js/blob/master/examples/thing-example.js

**Comment by wjy617** [comment]
@fengsongAWS @rpcme  Thanks for responding.  I understand thingShadow.on('delta') will receive delta when thingShadow is connected, but it will miss the delta coming in when disconnected. My question is whether there is some command which can only get the missed delta instead of getting the whole shadow by thingShadow.get()?

**Comment by rpcme** [comment]
Ah OK, I understand you now.  In this case, as far as I'm aware you will need to get the whole document.  Yet, the delta will still be in the get() contents, so you don't have to compute deltas yourself. 

The way I think about it is:  if my device disconnected, and then reconnected, it is effectively in an initialization state so it's likely the document should be run through to get the device "caught up".  Also, I think it's better operationally because if it saved a bunch of "delta messages" then it could happen many messages would need to be run through.

Finally, there isn't a topic to get a "delta only summary":
http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-mqtt.html

If this doesn't work out maybe I need the case elaborated on.

**Comment by fengsongAWS** [comment]
Thanks @rpcme for the response. Yes, the only way to catch the missing updates is through shadow.get() command after being reconnected. Since client does not know how many updates happening to server during disconnected period, all it cares is whatever the last state is. So, 'get' is the only way to sync up with server. All the updates for the desired state happened during disconnected period, if no other clients dealing with that, would be ignored. 

Thanks,
Fengyi

**Comment by wjy617** [comment]
Thanks @rpcme and @fengsongAWS  for your responses, which answer my question.

**Comment by fengsongAWS** [comment]
Thanks again. This could be a good reference for people who has similar questions. I will close this issue and feel free to open another one if you have issues in AWS IoT Node.js SDK
