### ISSUE TITLE
Size and MQTT

### ISSUE THREAD

**Issue by Auxolust** [aws/aws-iot-device-sdk-js#11]
Hi guys 

I'm really keen to use aws iot alot more, but I have some pressing concerns using mqtt currently.

The current size of the module is ~ 12.1mb on my machine with mqtt contributing 11.6 mb, as well as adding in a build phase on the initial install, is there no leaner alternative to this that we can use leveraging net sockets without native build phases? I don't want to push my own agenda but I use my websockets/net library called truflux when I need to have persistent connections and it contributes only 156kb whilst also allowing streaming and a protocol framework. My personal branch I'm working on is only about 720kb.

I understand however that you might need to reconfigure aws' backend to account for this, so I only ask, is it possible we seek an alternative?

**Comment by gkwicker** [comment]
Hi Auxolust,

Thanks for your input on our Node.js device SDK.  For memory constrained environments we would recommend using the Embedded C SDK rather than the Node.js SDK, as it can be built into much smaller executables.  As for using websockets to achieve persistent connections, the AWS IoT platform does not currently support this; however we are always evaluating new technologies and strive to provide the best possible service for our customers.  We're going to close this issue for now, but please re-open it if you have other questions on this topic.
