### ISSUE TITLE
Message sent callback

### ISSUE THREAD

**Issue by dushyantbangal** [aws/aws-iot-device-sdk-js#121]
Any way to know if the message has been sent or not?
I didnt find any callback that is invoked when the PUBACK is received from the AWS IoT Broker.

I need to set the sync flag on the device side, so that I would know the data has been sent.

**Comment by bxpan** [comment]
Hi dushyantbangal,

There is a callback function you may provide as part of publish function call:  https://github.com/mqttjs/MQTT.js/blob/master/README.md#publish 
Is this what you are looking for?

Thanks.

**Comment by dushyantbangal** [comment]
@bxpan I had used that initially. But it fired without `err` even though I had disconnected form the network

**Comment by fengsongAWS** [comment]
Hi @dushyantbangal ,
Are you using QOS 0 or QOS 1?

If using QOS 0, from the MQTT 3.1 spec, the client side does not care about whether the message has been successfully received by the server or not. In this case, the MQTT.js (dependency of AWS IoT Node.js SDK) will just trigger the callback. 

If using QOS 1, the call back will be triggered upon receiving puback from server because QOS1 will guarantee the message will arrive the server. 

However, if the client is disconnected, you should expect to see an error thrown from callback.

**Comment by dushyantbangal** [comment]
Sorry, I thought QOS 1 was default. It started working when I specified `{qos:1}` in options
