### ISSUE TITLE
subscribe(forbiddenTopic) results in disconnect

### ISSUE THREAD

**Issue by mvayngrib** [aws/aws-iot-device-sdk-js#125]
the websocket gets closed on AWS's side. After reconnect, the socket disconnects again, going into a connect-disconnect-backoff loop

**Comment by fengsongAWS** [comment]
Hi @mvayngrib ,
Are you using cognito or your own IAM User?
What is your IAM Policies that attached to your IAM user? Did you have full access of Iot?

**Comment by mvayngrib** [comment]
@fengsongAWS i forked the project from here https://serverless.com/blog/serverless-notifications-on-aws/  (github repo: https://github.com/zanon-io/serverless-notifications)  

Then I set the policy to restrict Subscribe and Receive topics by ${iot:ClientId} ...maybe i can push the fork and you can try it yourself?

**Comment by fengsongAWS** [comment]
Are you trying to do subscription when you restrict Subscribe action? If so, disconnect is expected because the server will close the connection if client does not have authorized action.

**Comment by mvayngrib** [comment]
@fengsongAWS yes, you understood it exactly. Could I ask you a couple of short questions about that? Thanks in advance!

Is disconnecting as a result of an unauthorized subscription a part of the MQTT protocol or an AWS thing? 

Is there a way for the client to know that the connection has been closed because the subscription was unauthorized?

Is there a way for the client to determine whether they have access to a topic, before subscribing?

**Comment by fengsongAWS** [comment]
Hi @mvayngrib ,
These are good questions and thanks for asking.
1. Is disconnecting as a result of an unauthorized subscription a part of the MQTT protocol or an AWS thing?
A: I would say both. MQTT is a long live connection. Unlike HTTP which could give you response code, based on mqtt protocol, if anything happens "unexpected", server should just kill the connection. In AWS IoT world, unauthorized subscription is  not allowed, the server should kill the connction. 

2. Is there a way for the client to know that the connection has been closed because the subscription was unauthorized?
A: No. Client has no way of knowing why the connection has been closed unless it close it by itself. 

3. Is there a way for the client to determine whether they have access to a topic, before subscribing?
A: If you use certificate based MQTT connection, you should have IoT Policy attached to that certificate and in that policy, where you could predefine the actions and resources for that cert. If you use mqtt over websocket, similarly, you have IAM Policy attached to your IAM User/Role. There is no mqtt level API that could get you any information of access but aws iot control plane API which is based on HTTP protocol could give you more. http://docs.amazonaws.cn/cli/latest/reference/iot/index.html. However, this is assuming that the IAM credentials you are using to call this cli has correct access to these resources beforehand.

**Comment by mvayngrib** [comment]
@fengsongAWS thank you for the detailed response! I'll need to mull the answer to 1. over, something doesn't sound right about just terminating the connection, but if there isn't an MQTT protocol-level message saying: "you can't subscribe here", maybe it's a reasonable response. 

One quick follow-up question: why does the client get repeatedly disconnected after re-establishing the connection? I'm pretty sure I'm not re-running `client.subscribe(unauthorizedTopic)` on reconnect. Do you happen to know if it's client-side caching and resubscribe-on-reconnect or if that clientId just gets blacklisted server-side?

**Comment by fengsongAWS** [comment]
Hi @mvayngrib ,
The server has no control over which topic the clients subscribe on, so I think that's why there's no MQTT level message. Or it could send message to TCP socket but that definitely beyond MQTT level specification. 

The client SDK does have offline queue that store and resub upon reconnect. You can disable auto resubscribe option in your device option. 

Thanks

**Comment by fengsongAWS** [comment]
Please feel free to reopen this issue if you still have problems.
