### ISSUE TITLE
Correct handling of getaddrinfo ENOTFOUND

### ISSUE THREAD

**Issue by r1ch** [aws/aws-iot-device-sdk-js#130]
Hi - firstly thanks for a great library and documentation!

I've got a Node.js implementation that runs headlessly on a Raspberry Pi - it happily ticks away for a week or so until - (thanks to flakey WiFi) I see it's rebooted courtesy of:

```
{ Error: getaddrinfo ENOTFOUND xxxxxxxxx.iot.region.amazonaws.com xxxxxxxxx.iot.region.amazonaws.com:8883
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'xxxxxxxxx.iot.region.amazonaws.com',
  host: 'xxxxxxxxx.iot.region.amazonaws.com',
  port: 8883 }
```
This is a genuine error that the library is surfacing - DNS can't resolve during the period of flakey WiFi. However I'd like to do something better than just crash out... (e.g. exponential back off, retry the connection etc.).

I'm using the suggested pattern of `clientTokenUpdate = shadow.update('ThingName', update);` and wrapping that in a try/catch isn't getting me anywhere (I presume because it becomes asynchronous later?). Do you have any recommendation as to how I can stop the behaviour from bringing down my application.

Currently I've got the widely discouraged code below, which is able to keep me in business but it's a shame given how neat everything else is!

```
process.on('uncaughtException', function (exception) {
        console.log(exception);
});
```

Rich

**Comment by r1ch** [comment]
So a much better start that the `process.on('uncaughtException',(error)=>{})` is using the library's `device.on('error',(error)=>{})` so we are catching the error much closer to home.

If I'm happy that the error is due to a temporary DNS issue is there anything that I can actually do in the error handler - other than just drop it? It seems that if the error is caught then the library carries on merrily when the next update is attempted.

**Comment by fengsongAWS** [comment]
Hi @r1ch ,
Thanks for your interest in IoT Device SDK. Can you try this commit and see if it helps?
https://github.com/aws/aws-iot-device-sdk-js/pull/131/commits/12d693edb3d31e12625bdb2f277d3fcd8ba1e78a

Thanks

**Comment by SRHradiologycourse** [comment]
Looks good. I'll wait for a few more "natural" WiFi drop outs then start simulating them.

Thanks

**Comment by r1ch** [comment]
Yes, seems to be doing the trick. I'll wait for it to catch a few more "natural" WiFi drop outs then start breaking it more deliberately!!

**Comment by r1ch** [comment]
0 issues in 19 days

Thanks - will close

**Comment by Tin-Man-Dylan** [comment]
This was helpful to me, and I guess now it also starts a reconnect sequence as can be seen in here https://github.com/aws/aws-iot-device-sdk-js/blob/master/device/index.js . However one thing that I found this doesn't solve is if when first starting your program that you do not have internet connectivity. For me it gave me the exact same error as originally presented here.

`
Error: getaddrinfo ENOTFOUND data.iot.us-west-2.amazonaws.com data.iot.us-west-2.amazonaws.com:8883
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:26)

`

In order to fix this I just used the event emitter to catch errors and instead print something to console (eventually I will use it for some more feedback). Since it automatically tries to connect again if there is no error this works for me. Not sure if this is the best way to do this though
`
device.on('error', function (err) {
    console.log("Unable to connect to AWS, or other problem");
});
`
For all of this I am on a raspberry pi zero W, and to test it with the internet cutting off in the middle and starting with it off i just use "sudo ifdown wlan0" to turn of and "sudo ifup wlan0" to turn on

Now I do have one question about event emitters, as seen above the device.on('error', function()) one does work for me, also the 'connect' one and the 'message' one too. So I assumed the rest of them from MQTTjs would work as well since it is built on it.

However when I try to use ones like 'close' and 'reconnect' and just do a console log they don't seem to always react to the loss of internet. They do seem to show when I have the internet not connected from the beginning, but if I shut it off (ifdown) in the middle of it running the event emitters don't display anything. Is there something I am doing wrong? Because it seems as though they must be working [here](https://github.com/aws/aws-iot-device-sdk-js/blob/master/device/index.js) since it reconnects.

Thanks for the help. I can open this as a new issue if that is better.
