### ISSUE TITLE
support for browser environment using mutual certificate authentication

### ISSUE THREAD

**Issue by 0xc0d3r** [aws/aws-iot-device-sdk-js#136]
Duplicate of #76 

I am getting above issue while integrating aws-iot-device-sdk-js with certificate authentication method. I am using [buffer](https://github.com/feross/buffer) for browser env. But still code is breaking at [tls-reader.js](https://github.com/aws/aws-iot-device-sdk-js/blob/master/common/lib/tls-reader.js#L89). 

When will you guys provide support for browser environment?

Is there any hacks to over come this error?

**Comment by fengsongAWS** [comment]
Right now, the preferable method on browser environment is through mqtt over webscoket. You can either use cognito or IAM credentials. 

Thanks,
Fengyi

**Comment by 0xc0d3r** [comment]
@fengsongAWS 
Do you guys have road map for this feature?

**Comment by fengsongAWS** [comment]
Hi @0xc0d3r ,
This is usually not a recommended way of hardcode certs and keys in browser environment so that we have cognito service for mobile and web developers. We will look into this and collect more customers data about this feature request. Meanwhile, if you have anything that helpful on this, please feel free to submit a pull request.

Thanks for your interest in AWS IoT Device SDK.

**Comment by 0xc0d3r** [comment]
Thanks for the reply @fengsongAWS 

Actually we are not hardcoding the certs and keys at client side. We will get them from our backend server when the user login. Our use case is like for every user we will have publish and subscribe topics and we'd to like to achieve topic authorisation and restriction. Based on the clientId we are differentiating the multiple logins of the same user in different devices.

**Comment by fengsongAWS** [comment]
You could also achieve that by using cognito where you create user pools with different authorized roles which has different permissions. 

Or you could try with buffer.js and modify the SDK code to take buffer instead of using fs.

**Comment by 0xc0d3r** [comment]
Thanks for the reply @fengsongAWS 

For now, I am implementing with Cognito poolId.

**Comment by fengsongAWS** [comment]
Thanks for your interest in AWS IoT Device SDK. We will close this issue for now and please feel free to open another thread if you have more questions.

**Comment by superandrew** [comment]
Hi, jumping in in this closed issue since we're struggling using the aws-iot-sdk in browser with ionic but it seems pointless to open a new issue. 

@fengsongAWS could you please confirm that we *need* to use cognito pool authentication or is there a "certificate/key" way of doing it? We tried with buffers and browserify, to no avail, always ending with fs.existsSync is not a function. In our model an authenticated user is calling a cloud function on a lambda to get a certificate, which would be then used to communicate via mqtt from the browser ionic app.

Any help/link would be greatly appreciated.

**Comment by 0xc0d3r** [comment]
Hi @superandrew,

Currently, they are not supporting it for the browser environment. As per my previous experience, you have to proceed with cognito pool Id only.
