### ISSUE TITLE
The security token included in the request is invalid. - Lambda - IOT

### ISSUE THREAD

**Issue by mveera21** [aws/aws-iot-device-sdk-js#146]
Hi,

We are on AWS IOT, and I've setup everything 3 weeks ago. 
It's been working great since I set up, but it failed today with the following error.

I haven't changed any policies, and no one else has access to my account. 

Benefit  of doubt, I attached "IOT full access" policy t my Lambda rule, but it's still failing.

**Error:**
2017-09-07T05:43:22.249Z	734caa95-938f-11e7-87af-5350e6ad1d43	{ ForbiddenException: The security token included in the request is invalid.
    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:48:27)
    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)
    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)
    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:685:12)

**Policies attached to my role:**

AWSLambdaBasicExecutionRole-8a08e2cf-887c-4b7b-873e-49a101bb53ec 
AmazonDynamoDBFullAccess 
AWSLambdaInvocation-DynamoDB 
AWSIoTFullAccess
AmazonSNSFullAccess

Could you please help me to understand this issue? I was hoping that AWS IOT is more reliable.

Thank you,

**Comment by groteworld** [comment]
Hi @mveera21,

The error you are getting here seems to be coming from [aws/aws-sdk](https://github.com/aws/aws-sdk-js), not from this repository, which is the AWS IoT Device SDK. That said, I'll try to help still. 😄 This issue typically happens when using AWS Credentials (AccessKey and SecretKey) that are invalid. I would check that the lambda is using valid credentials still. 

Hope that helps!

**Comment by mveera21** [comment]
Thanks for your response! I'm testing my lambda function through AWS console only. My lambda function is publishing message using IOT. When I tried from IOT console, it still works fine. I hit this issue only when I try to run it from Lambda function. And everything worked till last yesterday.

Any clues?

Thank you!

**Comment by mveera21** [comment]
Lambda function is getting kicked off fine, and it prints logs when I test form the AWS console or outside AWS console( My App), but it's failing only when lambda function tries to publish IOT message which was working fine till yesterday. By the way AWS has very good support on testing in the consoles. This feature is very helpful to debug issues.

**Comment by groteworld** [comment]
Based off of the information I've seen here, it definitely sounds like the credentials your lambda is using are not valid to connect through [aws/aws-sdk-js](https://github.com/aws/aws-sdk-js) to AWS IoT.

Do you allow the lambda to determine its credentials, or do you have them in environment variables or hard coded? 

The gist below is an example I made using [aws/aws-sdk-js](https://github.com/aws/aws-sdk-js) to publish mqtt messages from a lambda. Maybe it will help?
https://gist.github.com/groteworld/af0577ea5c59e98843ef47325407da71

Otherwise you may need to make a ticket in [aws/aws-sdk-js](https://github.com/aws/aws-sdk-js) or wait for an admin in this repo to help you troubleshoot this.

[AWS Developer Forums](https://forums.aws.amazon.com/index.jspa) are also extremely helpful!

Sorry if I can't be any more help

**Comment by mveera21** [comment]
Thank you @groteworld for your initial analysis.  I'm leaving lambda to determine its credentials, and I've not hard coded any keys. It's been working great till yesterday. Without any changes, it's broken today. My lambda function writes/reads DynamoDb and publishes messages to IOT. Everything was working for the past few weeks, and only IOT is broken today. Writing and reading to DB are working fine within the same function. Also, if test directly from IOT Test console, tings are working. I'm not suer what is changed from AWS side. Is there any some expiration on lambda functions/ policies/rules? 
Thanks
