### ISSUE TITLE
autoResubscribe is not work when there are many topics subscribed

### ISSUE THREAD

**Issue by sanpechuda** [aws/aws-iot-device-sdk-js#147]
When I connected broker and then subscribe to 25 topics, I cannot resubscribe after reconnection. 
However, I found that if I subscribe to less topic(such as 8 topics), I can resubscribe after reconnection.

Now, I have to manually unsubscribe each topic before subscribing them.

**Comment by fengsongAWS** [comment]
Hi @sanpechuda ,
Thanks for pointing this out. The root cause of this issue is that mqtt.js handle all the topics into one subscribe operation. The AWS IoT limit per subscribe to 8 topics so that's why you only saw it works for topics less than 8. A work around of this is that disable mqtt.js resubscribe. However, mqtt 2.2.1 does not expose this option. You can manually upgrade to latest mqtt.js  and set options.resubscribe to true but leave autoResubscribe to true for aws-iot-device-sdk. This will allow aws-iot-sdk to handle the resubscribe for you. We will fix this in the future release.

Thanks

**Comment by fengsongAWS** [comment]
Issues fixed v2.2.0
