### ISSUE TITLE
connection lost - will attempt reconnection in 8 seconds...

### ISSUE THREAD

**Issue by akashbiz** [aws/aws-iot-device-sdk-js#173]
Hello, I am using cognito to authenticate users and then creating a thing for each user and attaching the identity as principal to this newly created thing. This flow works great with **temperature monitor example** but if we delete cognito user and re signup with same credentials then identityId is different now and hence connection isn't establishing properly because this new Identity is not attached to thing. I am just getting connect lost message. Please see below console logs:

`
canonical request: GET
/mqtt 
X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=credentials%2F20171221%2Fus-east-1%2Fiotdata%2Faws4_request&X-Amz-Date=20171221T062241Z&X-Amz-SignedHeaders=host
host:xxxxxxxxxxxxxx.iot.us-east-1.amazonaws.com

hashed canonical request: dcb90b2e32d2d672d49837d88a67a404de076275d0c4659f1ba0f20cd6bdbc60

string to sign: AWS4-HMAC-SHA256
20171221T062241Z
20171221/us-east-1/iotdata/aws4_request
dcb90b2e32d2d672d49837d88a67a404de076275d0c4659f1ba0f20cd6bdbc60

signing key: <key>

signature: <signature>

url: wss://xxxxxxxxxxxxx.iot.us-east-1.amazonaws.com/mqtt?X-Amz-Algorithm=AWS4-…lVdkb2EeJzsxnCtMZF2EDd4NEyZKJ%2BTaOSjsN%2FqILRt%2FYEmmUv8IGFHUwq6bt0QU%3D

using websockets, will connect to 'wss://xxxxxxxxxxxxx.iot.us-east-1.amazonaws.com/mqtt?X-Amz-Algorithm=AWS4-…

connection lost - will attempt reconnection in 4 seconds...

reconnecting...
request: GET
/mqtt
X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=credentials%2F20171221%2Fus-east-1%2Fiotdata%2Faws4_request&X-Amz-Date=20171221T062247Z&X-Amz-SignedHeaders=host
host:xxxxxxxxxxxxx.iot.us-east-1.amazonaws.com

hashed canonical request: 09a54e3c77937628ddcd19c2c08a94aafd13fea50af1fbf24094b4a9a793e00e

string to sign: AWS4-HMAC-SHA256
20171221T062247Z
20171221/us-east-1/iotdata/aws4_request
09a54e3c77937628ddcd19c2c08a94aafd13fea50af1fbf24094b4a9a793e00e

signing key: <key>

signature: <signature>

url: wss://xxxxxxxxxxxxx.iot.us-east-1.amazonaws.com/mqtt?X-Amz-Algorithm=AWS4-…lVdkb2EeJzsxnCtMZF2EDd4NEyZKJ%2BTaOSjsN%2FqILRt%2FYEmmbUv8IGFHUwq6bt0QU%3D

using websockets, will connect to 'wss://xxxxxxxxxxxxx.iot.us-east-1.amazonaws.com/mqtt?X-Amz-Algorithm=AWS4-...

connection lost - will attempt reconnection in 8 seconds...
`

**Comment by juhamust** [comment]
Same issue here - but I didn't have to to delete/re-register the user between 🤔

**Comment by juhamust** [comment]
Having similar issue with the built-in example: https://github.com/aws/aws-iot-device-sdk-js/tree/master/examples/browser/mqtt-webpack

Cognito _does return_ valid looking accessKeyId, secretKey and sessionToken, but still console keeps returning error:
```
VM2520:164 WebSocket connection to 'wss://blahblahblah.auth.eu-central-1.amazoncognito.com/mqtt?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=BLAHBLAHQRGUF3VTLIU7A%2F20171228%2Feu-central-1%2Fiotdevicegateway%2Faws4_request&X-Amz-Date=20171228T175603Z&X-Amz-SignedHeaders=host&X-Amz-Signature=blahblahblahblah5cd1d13b5d8f09ba42c4a1fb52443747e3b62e93f9134627dd&X-Amz-Security-Token=blahblahblahGV1LWNlbnRyYWwtMSKAAhtcrKdlIGYUmAo4h2xSx93J%2BWz44JRjJuy8L3LU60eLpX%2BwMqjVs7j%2FeLjL%2FjXmeEXOvXTPFvRtyF1efdd8xP%2F8KRr4YiF64rBI3xc6hqwcznSgHJRlzycB7DOj...3IfShyLX%2Fen%2FUQJhVfzXWJPlelKvgeRUocbGM%2Fja7S0vT1nTrU2KaTeqIJ%2BlDydbjq9YBeNTgX5lply60Z%2Bb9I%2BNk1fe1rAMh0OvlIuHryKkKuUriuq95ljSZ7x4FEFX2d1erEksGZtTXRrN5U8nk5a61oiff5pMS3jQYpzoe8IxnVHg9YpWO2xRld%2BJJgsxf4aMP2zIMm5PkBiv%2BM2z4bLMwEI7afnM64w8vLrHXqQBcTfkZF0cuw91Gi0R6jBXpSe3nn5k4%2FsvukBCItIYJbwFOMbSKkOrIaQoZrK1VJCrRNx5X6vtZxAXERHFi%2Bnrs88xLGacefllBLAHUoSShYwKZhHfV6EUtB6rJcYD9UrRfzRbP9h2VtIzAlYchqPIbBlJa0dsSC0rqID5mKiKCnKJ%2F5qE6C75egRWZpGjsOlGVYTLDU2vV%2B%2BXew08VPgu6fGp%2BnevfUB%2F34vMq3NFwK0wruCU0gU%3D' failed: Error during WebSocket 
bundle.js:20151 Event {isTrusted: true, type: "error", target: WebSocket, currentTarget: WebSocket, eventPhase: 0, …}
bundle.js:9901 connection lost - will attempt reconnection in 2 seconds...
bundle.js:20089 reconnect
```

**Comment by fengsongAWS** [comment]
Hi,
The SDK basically does not do any authentication for users. It basically passes all the credentials to server and return messages from server. Since your AWS credentials work for websocket connection, I doubt there were some misconfiguration for your cognito settings. Could you double check your permission, policy and enable unauthenticated login if using this way?

Thanks

**Comment by fengsongAWS** [comment]
Yes, please refer to cognito developer guide for more details here. 
https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-console.html

**Comment by gpcrawford** [comment]
I too am seeing this issue when trying to implement the browser/mqtt-explorer example.  I am authenticating from the browser using Cognito user pools and identities and I know the authentication works because I can access a dynamodb table from browser code after authenticating (the cognito role allows dynamodb access).  The cognito auth role includes full AWS Iot Access permissions.  I have enabled unauthenticated login.  However, I am seeing debug output in the console exactly as described by the original post above.

**Comment by fengsongAWS** [comment]
A common mistake is mismatch of region. Please make sure your region of your cognito matches your IoT region. Did you attach your policy to unauthenticated role?

**Comment by gpcrawford** [comment]
Is there any reason that authenticated identities can't be used?

**Comment by juhamust** [comment]
@gpcrawford care to share a link into documentation describing how to do it? thanks.

**Comment by gpcrawford** [comment]
@juhamust - this thread was very helpful in pointing me in the right direction: [https://github.com/aws/aws-iot-device-sdk-js/issues/155](url)

The key ingredient is attaching the policy defined in the IoT console for your thing to your authenticated identity.  This is pretty straightforward and is done with the AWS.iot.attachPolicy method ( [https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/Iot.html#attachPolicy-property](url) )

For development purposes, my IoT policy is defined as:
```javascript
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": [
        "iot:*"
      ],
      "Resource": "*"
    }
  ]
}
```

(Note that this policy is defined in AWS IoT - I used the AWS IoT console to do so.)

For example if your policy is named "MyIoTPolicy" and in your code you have your credentials in AWS.config.credentials and your MQTT client is setup as mqttClient you could use the following:

```javascript
var iot = new AWS.iot();

var policyParams = {
  policyName: "MyIoTPolicy",
  target: AWS.config.credentials.identityId
};

iot.attachPolicy(policyParams, (err, data) => {
  if (err) {
    console.log("ERR - Attaching policy: "+err)
  }
  else {
    console.log("Policy successfully attached.");

    //Now that policy is attached, set credentials for MQTT client
    this.mqttClient.updateWebSocketCredentials(
      AWS.config.credentials.accessKeyId, 
      AWS.config.credentials.secretAccessKey,
      AWS.config.credentials.sessionToken
    );

  }
})
```

Originally, I tried the full ARN for the IoT policy but it turns out that you only need the name (MyIoTPolicy in this case).

Note that I think you **also** need that the IAM role for the authenticated identity have access to IoT (For dev purposes I am using the AWSIoTFullAccess policy attached to the IAM role) 

I can provide more details if needed.

**Comment by juhamust** [comment]
Thanks a lot @gpcrawford  for thorough instructions! I'm sure I can take it from there - but will ask/add comments if needed.

**Comment by fengsongAWS** [comment]
Hi all,
Thank you for your interest. @gpcrawford is correct that you should attach policy to your principal. Please let us know if you have more questions.

**Comment by juhamust** [comment]
Thanks for the helpful tips and instructions from my behalf as well. Finally managed to create WS connection. Had one more additional reason for re-connection issue: Too limited IAM role permissions. While I don't have the exact list of actions needed, that is something to check and adjust in case of having same error. 

All in all, seems like there are several possible problems developer can run in to. Therefore, these steps should be documented better both in project documentation and examples to avoid future headaches. 👍

**Comment by fengsongAWS** [comment]
Please open another thread if you still have questions.
