### ISSUE TITLE
Can't handle Error: Error: write EPROTO

### ISSUE THREAD

**Issue by lukin0110** [aws/aws-iot-device-sdk-js#18]
In `device/index.js` an error will be thrown if there are problems with SSL. In our use case it might happen that we revoke certificates server side but this causes the application to crash. Is is possible to move the `new Error` code to a callback or pass it with EventEmitter?

This causes the crash:
```
 //handle some exceptions
  device 
    .on('error', function(error) {
      //certificate issue
      if (error.code === 'EPROTO') {
        throw new Error(error);
      }
    });
```

Or how do we have to treat this situation?

**Comment by gkwicker** [comment]
Hi Maarten,

Thanks for your question; we agree that it may sometimes be beneficial to log an error rather than throwing an exception for an invalid TLS configuration.  If you'd like to handle this error in your application, just delete that block of code (the one in your post) from device/index.js.  You might notice that the example programs (e.g. device-example.js) install their own handlers on the error event anyway.

We'll consider this modification for a future version, and thanks again for helping us improve the SDK.  We'll close this issue for now, but feel free to re-open it if you have further questions on this topic.
