### ISSUE TITLE
Testing?

### ISSUE THREAD

**Issue by dsshap** [aws/aws-iot-device-sdk-js#19]
Any suggestions on how to use this lib in testing (mocha)?

**Comment by gkwicker** [comment]
Hi Dave,

If you are unit testing an application which uses this SDK, you might consider mocking the SDK calls so that you're only exercising your code and don't need to connect to the AWS IoT platform.  In addition to mocha, there are many other JavaScript testing frameworks and utilities available.  [sinon](https://github.com/sinonjs/sinon) is one which can help mock calls to other pieces of software outside of your application; this might be useful in your unit tests.

**Comment by dsshap** [comment]
Mocking the calls is the plan, please provide a pattern that you are using internally. 

As there are no spec's found in the SDK (publicly) to model our tests after.

**Comment by gkwicker** [comment]
Hi Dave,

Thanks for letting us know that there's interest in having published unit tests for this SDK.  It's always helpful for us to find out how customers are using our SDKs and how they can be improved to be more useful.  We are planning on publishing the unit tests for this SDK in a future release, but we don't have a date for this right now.  Please feel free to let us know of any other feature requests or additions that you'd like to see added.

**Comment by gkwicker** [comment]
Hi Dave,

Just wanted to let you know that the latest version (1.0.10) includes unit tests and code coverage; just do 'npm test' to run the tests and generate coverage data.
