### ISSUE TITLE
subscribing to an unauthorized topic causes connect/disconnect loop

### ISSUE THREAD

**Issue by benariamir** [aws/aws-iot-device-sdk-js#191]
I've set an IAM policy such that a device can not subscribe to a topic named 'unauthroizedTopic'.
As expected - device was disconnected from AWS IoT.

Problem is that because autoResubscribe is on -> after it reconnects it tries to resubscribe to unauthroizedTopic, and again disconnects -> connects -> resubscribe --> disconnects --> connects --> resubscribe and so on.

No custom code to attach, just used the examples.

**Comment by hedeshianaws** [comment]
Thank you for using the AWS IoT SDK.  As you have observed, IoT will drop the connection in the event of an unauthorized subscription. Unfortunately, there is no error code or disconnect reason relayed to the client. That means that the SDK cannot intelligently determine that the re-subscription to the unauthorized topic is the cause of the disconnect. 

Unfortunately, I don't think there is a generic answer here that will satisfy all users of the SDK. If we were to make the SDK behavior such that disconnect after subscribe would cause the SDK to reconnect without re-subscribing, we'd be breaking all users who expect re-subscribe to do its job: topics to be correctly resubscribed. This would also mean that any network interruption during the re-subscription process would cause the SDK to trigger this fallback behavior even if it is not necessary. And finally, a momentary incorrect IAM policy could inadvertently cause device SDKs to behave unexpectedly instead of simply recovering.

**Comment by hedeshianaws** [comment]
Miscategorized as bug, changing to enhancement.

**Comment by cenxui** [comment]
This is really useful!! Thanks

**Comment by jmklix** [comment]
Sorry, but it appears that this is an old feature request and we are no longer accepting any feature requests for this sdk as it is being sunsetted. The [V2](https://github.com/aws/aws-iot-device-sdk-js-v2) sdk is accepting feature requests.
