### ISSUE TITLE
Can this library be used as Mqtt bridge

### ISSUE THREAD

**Issue by goyalhonney** [aws/aws-iot-device-sdk-js#204]
I am planning to use a ec2 server which acts as a bridge between aws iot and my mobile devices.
I read that this can be implemented using mosquitto bridge and aws-iot. 
But which will have better performance mosquitto bridge or aws-iot-device-sdk library. 
My main purpose is to Subscribe to topic for mqtt.

**Comment by fengsongAWS** [comment]
The aws iot device sdk library provides better support for onbaording aws iot. I do not have a clear understanding on which one has better performance regarding efficiency, CPU memory usage etc. This really depends on customer use cases. However, it is definitely less work and efforts by using device sdk in order to onboard with AWS IoT.

**Comment by fengsongAWS** [comment]
Please open another thread if you still have questions.
