### ISSUE TITLE
modify ThingShadow desired state from Lambda Function

### ISSUE THREAD

**Issue by 5e8a91** [aws/aws-iot-device-sdk-js#22]
Hi,
I'm trying to modify the shadow of a Thing from a lambda function, but my code still not works.
Someone can correct me?
Here is the code I used (this way  I obtain the following error from logs: "missing required node:state")
```
console.log('lambda function');

var AWS=require('aws-sdk');
var iotdata = new AWS.IotData({endpoint: 'my-end-point.iot.eu-west-1.amazonaws.com'});  

exports.handler = function(event, context){
var params = {
  payload: new Buffer('66') || '{"state": {"desired": {"windowOpen": false,"posto2": true}}}', 
  thingName: 'Edison_Seba' 
};
iotdata.updateThingShadow(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});

}
```

Another try of updating the shadow is(from logs I obtain: "{}" but it doesn't modify the shadow):
```
console.log('lambda function');

var AWS=require('aws-sdk');
var iotdata = new AWS.IotData({endpoint: 'my-end-point.iot.eu-west-1.amazonaws.com'});  

exports.handler = function(event, context){

var params = {
  topic: '$aws/things/Edison_Seba/shadow/update', 
  payload: new Buffer('60') || '{\"state\": {\"desired\": {\"windowOpen\": true,\"posto2\": true}}}', 
  qos: 0
};
iotdata.publish(params, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
});

}
```
Thank you

**Comment by gkwicker** [comment]
Hi,

It looks like you're working with the [AWS SDK for JavaScript](https://github.com/aws/aws-sdk-js), which uses HTTP to access AWS services; this repository is for the AWS Device SDK for JavaScript, which is for use in embedded devices and is based on MQTT.  Even though you're not using this package, I do see something wrong in both of your code samples.  You are assigning an empty buffer as the value of the 'payload' property (the '||' operator will stop once an expression evaluates as true).  To see what's happening, try running this little program:

```js
var params1 = {
  payload: new Buffer('66') || '{"state": {"desired": {"windowOpen": false,"posto2": true}}}', 
  thingName: 'Edison_Seba' 
};

var params2 = {
  payload: '{"state": {"desired": {"windowOpen": false,"posto2": true}}}', 
  thingName: 'Edison_Seba' 
};

console.log('***here\'s what\'s in \'params1\'***');
console.log(params1.thingName);
console.log(params1.payload);
console.log('\n***here\'s what\'s in \'params2\'***');
console.log(params2.thingName);
console.log(params2.payload);
```

When you run this program, you'll see something like this:

```sh
$ node index.js 
***here's what's in 'params1'***
Edison_Seba
<Buffer 36 36>

***here's what's in 'params2'***
Edison_Seba
{"state": {"desired": {"windowOpen": false,"posto2": true}}}
```
Modify your code to use the 'params2' initialization so that the 'payload' property has your JSON document in it, and give that a try.  If you're still having issues, I'd recommend posting your questions on the AWS forum or in the [AWS SDK for JavaScript github repository](https://github.com/aws/aws-sdk-js).  Thanks for trying out the AWS IoT platform.
