### ISSUE TITLE
TypeError: filesys.existsSync is not a function

### ISSUE THREAD

**Issue by samarahmad** [aws/aws-iot-device-sdk-js#245]
i have written this code in angular 5
but when i compile this code 
@fengsongAWS 

`import { Component } from '@angular/core';
import * as awsIot from "aws-iot-device-sdk";
import * as mqtt from "mqtt";
@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'app';
 constructor(){
 
 }
 device=new  awsIot.device({
  keyPath: "xxxxx",
 certPath: "xxxxxxx",
   caPath:"xxxxxx",
 clientId: 'mynodejs',
   host: 'xxxxxxxx'
})
 }`
i got error in browser 
ERROR TypeError: filesys.existsSync is not a function
    at module.exports (tls-reader.js:89)
    at new DeviceClient (index.js:455)
    at new AppComponent (app.component.ts:14)
    at createClass (core.js:12479)
    at createDirectiveInstance (core.js:12326)
    at createViewNodes (core.js:13784)
    at createRootView (core.js:13673)
    at callWithDebugContext (core.js:15098)
    at Object.debugCreateRootView [as createRootView] (core.js:14381)
    at ComponentFactory_.create (core.js:11278)
how can i solve this issue ###

**Comment by hieupaul** [comment]
+1

**Comment by Sourabh482** [comment]
How can remove this error from my ionic project.
not get the certificate path in ionic awsIOt object.
ERROR TypeError: filesys.existsSync is not a function
at module.exports (tls-reader.js:89)

**Comment by borch84** [comment]
Hi @Sourabh482 are you still having the error:  `filesys.existsSync is not a function` ?
I am having same issue when I inspect the console output from my web browser.
I am trying to implement a mqtt client in my ionic application using this sdk. 
I would like to summarize my actions in order to understand if this issue applies to me as well:
First thing I did was to install sdk with:

- `npm install aws-iot-device-sdk`

Then I had to install **@types/node** and modified **tsconfig.app.json**:

- `npm i @types/node`

Modify **tsconfig.app.json** with: `"types": ["node"]`

After these changes I was getting this errors:

`
[ng] ERROR in ./node_modules/aws-iot-device-sdk/common/lib/tls-reader.js
[ng] Module not found: Error: Can't resolve 'fs' in '/home/borch/Documents/Ionic/aws-iot-mqtt-client/node_modules/aws-iot-device-sdk/common/lib'
[ng] ERROR in ./node_modules/aws-iot-device-sdk/device/index.js
[ng] Module not found: Error: Can't resolve 'fs' in '/home/borch/Documents/Ionic/aws-iot-mqtt-client/node_modules/aws-iot-device-sdk/device'
[ng] ERROR in ./node_modules/aws-iot-device-sdk/device/index.js
[ng] Module not found: Error: Can't resolve 'path' in '/home/borch/Documents/Ionic/aws-iot-mqtt-client/node_modules/aws-iot-device-sdk/device'
[ng] ERROR in ./node_modules/aws-iot-device-sdk/device/lib/tls.js
[ng] Module not found: Error: Can't resolve 'tls' in '/home/borch/Documents/Ionic/aws-iot-mqtt-client/node_modules/aws-iot-device-sdk/device/lib'
[ng] ℹ ｢wdm｣: Failed to compile.
`
See post related posts: 
- https://github.com/aws/aws-iot-device-sdk-js/issues/235
- https://github.com/aws/aws-iot-device-sdk-js/issues/223

For these messages I applied this patch: https://gist.github.com/niespodd/1fa82da6f8c901d1c33d2fcbb762947d and I was able to resolve these **Can't resolve errors**. 

However I am getting now **TypeError filesys.existsSync is not a function**. 

From what I investigated, the preferable connection method on browser environment is through mqtt over websockets: 
- https://github.com/aws/aws-iot-device-sdk-js/issues/136
- https://github.com/aws/aws-iot-device-sdk-js/issues/76 
 
I've found these examples from the awslabs and from the aws-iot-sdk-js repositories:

- https://github.com/aws/aws-iot-device-sdk-js/tree/master/examples
- https://github.com/aws-samples/aws-iot-examples/tree/master/mqttSample

Has anyone been able to implement any of these examples using websockets on a Ionic application? Thanks.

**Comment by agabardo** [comment]
Amazon really needs to update this old dinosaur..
I have spent hours and hours and this aws-iot-device-sdk doesn't work with any Angular version larger than 4. Really a shame..

**Comment by typenai** [comment]
The IoT SDK will not work out of the box as a Browser script because FileSystem is a system module and it's not supported by a browser (duh!). You have to "browserify" the sdk by following the instructions there: https://github.com/aws/aws-iot-device-sdk-js#browser
