### ISSUE TITLE
Unable to run thing-example.js -- Doesn't subscribe to shadow topics

### ISSUE THREAD

**Issue by MikeDombo** [aws/aws-iot-device-sdk-js#262]
I'm trying to run the thing-example. I've modified it to use a thing name that I pass in from the command line, but it doesn't run properly. After inserting lots of console.logs I have found that it isn't subscribing to the required shadow topics. The device.subscribe in device/index.js:853 never calls the callback, either for success or error.

Any help getting this demo working would be great.

**Comment by kellydunn** [comment]
After a bit of troubleshooting, I was able to get the barebones example up and running; I think there's a bit of boilerplate AWS IAM + AWS IOT configuration you need to do first. I believe that in order to get the callbacks to flow, you need to have the following in place:

- An AWS IOT Policy similar to this, which you can create on AWS IOT > Security > Policies:

```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:Connect",
      "Resource": "arn:aws:iot:<region>:<account>:client/<thing>"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Subscribe",
      "Resource": "arn:aws:iot:<region>:<account>:topicfilter/$aws/things/<thing>/shadow/update/accepted"
    },
    {
      "Effect": "Allow",
      "Action": "iot:Receive", 
      "Resource": "arn:aws:iot:<region>:<account>:topic/$aws/things/<thing>/shadow/update/accepted"
    }
  ]
}
```

This policy will effectively allow the example to connect to your device, subscribe to when the shadow is successfully updated as well as receiving the data of the state afterwards.

- An AWS IOT certificate that you can attach the aforementioned policy to.  Once you've attached the policy, you can use that cert in the device example.

Here are pieces of the documentation I put together to get the example working: 
- IAM Policies for subscribing via MQTT https://docs.aws.amazon.com/iot/latest/developerguide/device-shadow-mqtt.html
- MQTT topics and TopicFilters: https://docs.aws.amazon.com/iot/latest/developerguide/topics.html
