### ISSUE TITLE
AWS IoT SDK Device Publish is Timing out on Lambda Function

### ISSUE THREAD

**Issue by universidadeglobal** [aws/aws-iot-device-sdk-js#321]
Hi,
I am using a aws sdk for nodeJs in my Lambda function to publish to AWS IOT Thing topic.
The payload is being published, I can confirm in test client in AWS IoT.
But for some reason it is generating a timeout in function.
I can configure any timeout value from 3 seconds to 3 minutes, the result is the same.
Below my code:
```

const device = awsIot.device({
            keyPath: './private.pem.key',
            certPath: './certificate.pem.crt',
            caPath: './ca_root.pem',
            clientId: makeid(10),
            host: 'aki0kv5z61fxo-ats.iot.us-east-1.amazonaws.com'
        });
        device
        .on('connect', function() {
          console.log('connect');
          device.publish('$aws/things/portao_automatico/shadow/update', 
              JSON.stringify({
                  state : {
                      desired : {
                          porta : "fechada"
                      }
                  }
          }));
      }); 
```

**Comment by bretambrose** [comment]
Hello,

Without knowing much about node/js, it seems possible that having an instantiated device creates one or more recurrent tasks that keep node alive indefinitely and that you'll need to add a callback that shuts down the device on the appropriate event (pub ack maybe, if you're just doing a one-time operation).

What happens when you run your code locally in node?

**Comment by universidadeglobal** [comment]
@bretambrose 
Thanks for reply.
I have changed my strategy. 
The objective is to use the code in Amazon Alexa Skill, and I have now tested with AWS SDK instead of AWS IOT SDK and works fine.
Thanks a lot.
