### ISSUE TITLE
While i m try to connect device than this message receive on console.app crash.

### ISSUE THREAD

**Issue by MurtuzaSrashtaSoft** [aws/aws-iot-device-sdk-js#351]
Confirm by changing [ ] to [x] below:
- [x] I've gone though [Developer Guide](https://docs.aws.amazon.com/iot/latest/developerguide/iot-sdks.html#iot-javascript-sdk) and [API reference](https://docs.aws.amazon.com/iot/latest/apireference/Welcome.html)
- [ ] I've searched for [previous similar issues](https://github.com/aws/aws-iot-device-sdk-js/issues) and didn't find any solution

**Platform/OS/Hardware/Device**
What are you running the sdk on?

**Describe the question**

```
 this.thingShadows = new awsiot.thingShadow({
      keyPath: keyPath,
      certPath: certPath,
      caPath: caPath,
      clientId: clientId,
      host: host,
    });
```

/Users/murtuzanalawala/Node/RiooNode/node_modules/end-of-stream/index.js:53
                if (readable && !(rs && (rs.ended && !rs.destroyed))) return callback.call(stream, new Error('premature close'));
                                                                                     ^
Error: premature close
    at onclosenexttick (/Users/murtuzanalawala/Node/RiooNode/node_modules/end-of-stream/index.js:53:86)
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
[nodemon] app crashed - waiting for file changes before starting...

**Logs/output**
If applicable, add logs or error output.

i m use this caroot certificate: https://www.amazontrust.com/repository/AmazonRootCA1.pem

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

**Comment by jmklix** [comment]
Can you please include the following info so I can better understand the problem that you are running into:

**Describe the bug**
A clear and concise description of what the bug is.

**SDK version number**

**Platform/OS/Hardware/Device**
What are you running the sdk on?

**To Reproduce (observed behavior)**
Steps to reproduce the behavior (please share code)

**Expected behavior**
A clear and concise description of what you expected to happen.

**Logs/output**
If applicable, add logs or error output.

*REMEMBER TO SANITIZE YOUR PERSONAL INFO*

**Additional context**
Add any other context about the problem here.
