### ISSUE TITLE
Can jobs and thingShadow share the same connection to device?

### ISSUE THREAD

**Issue by zhex900** [aws/aws-iot-device-sdk-js#392]
Hi,

Is it possible for jobs and thingShadow class to share the same connection with the device class? 

For example, 

````
var device = awsIot.device({
   keyPath: <YourPrivateKeyPath>,
  certPath: <YourCertificatePath>,
    caPath: <YourRootCACertificatePath>,
  clientId: <YourUniqueClientIdentifier>,
      host: <YourCustomEndpoint>
});

// this will create a new connection right?
// is it possible for jobs to use this same connection as device?
var jobs = awsIot.jobs({
   keyPath: <YourPrivateKeyPath>,
  certPath: <YourCertificatePath>,
    caPath: <YourRootCACertificatePath>,
  clientId: <YourUniqueClientIdentifier>,
      host: <YourCustomEndpoint>
});

````

Thank you

**Comment by bretambrose** [comment]
Each of those will be a separate device/connection, it looks like.

**Comment by jmklix** [comment]
@bretambrose is correct because you will have to use a [different endpoint](https://docs.aws.amazon.com/iot/latest/developerguide/iot-connect-devices.html) when connecting for IoT Jobs.

- IoT Core endpoint: `<account-specific-prefix>-ats.iot.<aws-region>.amazonaws.com`
- Jobs endpoint: `<account-specific-prefix>.jobs.iot.<aws-region>.amazonaws.com`
