### ISSUE TITLE
is it possible to subscribe to more than 7 shadows?

### ISSUE THREAD

**Issue by SubaruWRX55** [aws/aws-iot-device-sdk-js#43]
We are running into an issue where we can only subscribe up to 7 shadows. We get time out issue after number 7. Is it possible to subscribe to more than 7 shadows? 

Here is the test code:
```
var iotShadowConnection = awsIot.thingShadow(iotconfigParam);

    iotShadowConnection.on("connect", function () {
        console.log("Connected to AWS-iot");
    });

    iotShadowConnection.on("status", function (thingName, stat, clientToken, stateObject) {
        console.log("thingName: " + thingName + "\n stat: " + stat + "\n clientToken: " + clientToken + "\n stateObject: " + JSON.stringify(stateObject));
    });

    iotShadowConnection.on("timeout", function(thingName){
        console.log("Time out for " + thingName);
    });

    var deviceList = [  "876053d9-f549-4ad3-b036-e4fc7f05f642",
                        "7f86a005-530a-431d-8267-19572180b15c",
                        "61dcbcfd-3f21-4cfd-880c-9f540b3f24f2",
                        "91d98e0e-3b8e-4344-8239-f28d349dadf2",
                        "9793432d-53db-47a9-9c0e-c312110a9b70",
                        "e6c426d7-c3aa-4c14-bef5-de9c6c2880c3",
                        "f80095ac-219e-400e-a453-c611fcb23932",
                        "1698ace6-f6ae-4d16-96a2-f1b4b9de425a",
                        "b7edee1e-7107-4aa1-b18c-01c2fb324ac9",
                        "b297d5ed-8f28-4c96-b3df-bcf9cff18433"

    ];
    async.eachSeries(deviceList,function(device,callback) {

        iotShadowConnection.register(device);
        setTimeout(function(){
            iotShadowConnection.get(device);
            callback();
        }, 2000);
    });
```

Here is the result:

```
Connected to AWS-iot
thingName: 876053d9-f549-4ad3-b036-e4fc7f05f642
 stat: accepted
 clientToken: 847283250964-0
 stateObject: {"state":{"desired":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":"3364161a-91b0-4840-9d79-89b672e0c4cf"}},"delta":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":"3364161a-91b0-4840-9d79-89b672e0c4cf"}}},"metadata":{"desired":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":{"timestamp":1457485486}}}},"timestamp":1457644073}
thingName: 7f86a005-530a-431d-8267-19572180b15c
 stat: accepted
 clientToken: 847283250964-1
 stateObject: {"state":{"desired":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":"b0280274-c770-4bae-b502-3b210f01ece4"}},"delta":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":"b0280274-c770-4bae-b502-3b210f01ece4"}}},"metadata":{"desired":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":{"timestamp":1457485486}}}},"timestamp":1457644073}
thingName: 61dcbcfd-3f21-4cfd-880c-9f540b3f24f2
 stat: accepted
 clientToken: 847283250964-2
 stateObject: {"state":{"desired":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":"2c2dd796-ffc9-4f4b-be53-0e13aa870a98"}},"delta":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":"2c2dd796-ffc9-4f4b-be53-0e13aa870a98"}}},"metadata":{"desired":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":{"timestamp":1457485486}}}},"timestamp":1457644073}
thingName: 91d98e0e-3b8e-4344-8239-f28d349dadf2
 stat: accepted
 clientToken: 847283250964-3
 stateObject: {"state":{"desired":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":"76ddff04-4fcf-41f6-91d2-da2302c37765"}},"delta":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":"76ddff04-4fcf-41f6-91d2-da2302c37765"}}},"metadata":{"desired":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":{"timestamp":1457485486}}}},"timestamp":1457644073}
thingName: 9793432d-53db-47a9-9c0e-c312110a9b70
 stat: accepted
 clientToken: 847283250964-4
 stateObject: {"state":{"desired":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":"a9795375-08bd-410d-9f4a-e4e1090bafab"}},"delta":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":"a9795375-08bd-410d-9f4a-e4e1090bafab"}}},"metadata":{"desired":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":{"timestamp":1457485486}}}},"timestamp":1457644074}
thingName: e6c426d7-c3aa-4c14-bef5-de9c6c2880c3
 stat: accepted
 clientToken: 847283250964-5
 stateObject: {"state":{"desired":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":"b330658f-15cd-45a7-bcc6-b26d8fbedc61"}},"delta":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":"b330658f-15cd-45a7-bcc6-b26d8fbedc61"}}},"metadata":{"desired":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":{"timestamp":1457485485}}}},"timestamp":1457644075}
thingName: f80095ac-219e-400e-a453-c611fcb23932
 stat: accepted
 clientToken: 847283250964-6
 stateObject: {"state":{"desired":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":"2b5897b6-5ea2-49dc-b071-8af3aca099a5"}},"delta":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":"2b5897b6-5ea2-49dc-b071-8af3aca099a5"}}},"metadata":{"desired":{"settings":{"lock_codes":{},"daily_codes":[],"last_change_number":{"timestamp":1457485485}}}},"timestamp":1457644077}
connection lost - will attempt reconnection in 1 seconds...
Connected to AWS-iot
Time out for 1698ace6-f6ae-4d16-96a2-f1b4b9de425a
Time out for b7edee1e-7107-4aa1-b18c-01c2fb324ac9
Time out for b297d5ed-8f28-4c96-b3df-bcf9cff18433
```

**Comment by SubaruWRX55** [comment]
we also tried to create multiple connections by putting this line in the loop:
`var iotShadowConnection = awsIot.thingShadow(iotconfigParam)`, but also didn't work.

**Comment by liuszeng** [comment]
Hi @SubaruWRX55,

Thank you very much for using AWS IoT Node.js device SDK!

The root cause of this issue is that you have exceeded the limit of number of subscriptions for a single connection to AWS IoT, which closed the connection.

The [thingShadow class](https://github.com/aws/aws-iot-device-sdk-js#thingShadow) wraps an instance of the [device class](https://github.com/aws/aws-iot-device-sdk-js#device) and creates a connection to AWS IoT. It allows shadow operations (get, update, delete, delta) to be performed by subscribing to response topic and publishing MQTT requests to request topic. With default configuration option, where persistentSubscribe is set to true, 7 topics will be subscribed when a thing is registered. Suppose your thing name is "testThing", the following topics will be subscribed when `thingShadow.register("testThing")` is called:

    $aws/things/testThing/shadow/get/accepted
    $aws/things/testThing/shadow/get/rejected
    $aws/things/testThing/shadow/update/accepted
    $aws/things/testThing/shadow/update/rejected
    $aws/things/testThing/shadow/delete/accepted
    $aws/things/testThing/shadow/delete/rejected
    $aws/things/testThing/shadow/update/delta

The maximum number of subscriptions per session is 50 (See more details in [AWS IoT Developer Guide](http://docs.aws.amazon.com/iot/latest/developerguide/iot-limits.html)). The subscribe request that pushes the total number of subscriptions past 50 will result in the connection being disconnected, which will fail the connection in the process of registering the 8th thing in your code.

One thing you can do is to divide things into smaller groups using different connections. In that case, the total number of subscriptions per connection is reduced to be below the limit.

Hope that answers your question.

Thanks,
Liusu

**Comment by SubaruWRX55** [comment]
Can you provide an example of how to create a new MQTT session? I tried to
create a new thingshdow connection, but the first connection gets closed
when the second one is created.

- Clark

**Comment by liuszeng** [comment]
Hi Clark,

If you are using the same credentials for different connections to AWS IoT, make sure that the configured clientId for each connection is unique within your AWS account and region. Otherwise, the previous connection will get kicked out and closed. In the configuration options:

    var iotconfigParams1 = {
        ...
        clientId:"group1",
        ...
    };
    ...
    var iotconfigParams2 = {
        ...
        clientId:"group2",
        ...
    };

Then use different configuration to create different thingShadow instances:

    ...
    var iotShadowConnectionGroup1 = awsIot.thingShadow(iotconfigParams1);
    var iotShadowConnectionGroup2 = awsIot.thingShadow(iotconfigParams2);
    ...

From here, you can register things using two different connections and reduce the number of subscriptions per connection.

Thanks,
Liusu

**Comment by sagar1351** [comment]
How to remove timestamp from delta state??

**Comment by liuszeng** [comment]
Hi @sagar1351 ,

Thank you very much for your interest in AWS IoT Node.js SDK!

Delta messages emitted by the AWS IoT contains timestamps, which is the Epoch date and time the response was generated by AWS IoT. If you want to customize your delta messages, one thing you can do is to set up an AWS IoT rule to listen on your desired delta topic, look for the content you want and do a republish to another MQTT topic. By doing that, you will be able to filter out the timestamp. To see more information about AWS IoT rules, please check here: http://docs.aws.amazon.com/iot/latest/developerguide/config-and-test-rules.html

Note that this is a closed thread, please feel free to open up a new thread if you have more questions.

Thanks,
Liusu

**Comment by wahmedswl** [comment]
If someone want to do this today, then based upon the reference/support we settled on following pattern. 

You can create wildcard subscription and listen on them and use IoT Rule Engine to re-publish based upon that pattern. E.g. We subscribe on app/{deviceId}/sh/#. When you need to access data of the any shadow etc we publish on app/{deviceId}/sh/$aws/things/deviceId/shadow/get and based upon that, Rule Engine re-publish this to $aws/things/deviceId/shadow/get.
