### ISSUE TITLE
Custom CA

### ISSUE THREAD

**Issue by mcollina** [aws/aws-iot-device-sdk-js#54]
Following the guide http://docs.aws.amazon.com/iot/latest/developerguide/iot-dg.pdf, I'm trying to use my own CA (self signed according to the instruction in the guide) to issue certificates.

This is the error I am getting:

```
Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1065:38)
    at emitNone (events.js:80:13)
    at TLSSocket.emit (events.js:179:7)
    at TLSSocket._init.ssl.onclienthello.ssl.oncertcb.TLSSocket._finishInit (_tls_wrap.js:593:8)
    at TLSWrap.ssl.onclienthello.ssl.oncertcb.ssl.onnewsession.ssl.onhandshakedone (_tls_wrap.js:425:38)
```

**Comment by SomeoneWeird** [comment]
+1

**Comment by mcollina** [comment]
I think I found the issue. the `rootCA.pem` is always the same as it is the certificate used to verify AWS IoT MQTT broker.

**Comment by SomeoneWeird** [comment]
You mean the CA certificate you set up in the IOT UI on aws?

**Comment by mcollina** [comment]
so the certificate you pass as 'ca' option is always the same (the rootCa downloadable from the docs).

**Comment by yayolius** [comment]
@mcollina at least for me it was the only option that worked

**Comment by dushyantbangal** [comment]
I got this issue when I was using the [VeriSign Class 3 Public Primary G5 root CA certificate](https://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem) (which I got when I registered thing in `us-east-2`) instead of [Amazon Root CA 1](https://www.amazontrust.com/repository/AmazonRootCA1.pem) (which I got when I registered thing in `ap-south-1`)
I think they are using different rootCa for different regions, so even if you have one downloaded already,you need to make sure thats the one they give you when you use the "One Click Certificate creation"
