### ISSUE TITLE
Question: Packet Size Estimates MQTT

### ISSUE THREAD

**Issue by Hillsie** [aws/aws-iot-device-sdk-js#75]
Hi Guys, hope you don't mind me posting a question here about packet sizes. I don't seem to be able to find out how big a packet from a device might be when using MQTT + TSL, HTTPS or Websockets + security. I need these calculation to estimate data grow. Lets assume I was passing 10 metrics 12345.12345 for argument sake over to AWS IoT, how big might the packets be with MQTT and encryption? Just an order of magnitude would be a starting point.
Thanks in advance.

**Comment by rongsaws** [comment]
Are you concerning about the IP packet size limit or MQTT payload size limit? The MQTT payload for every publish message is limited to 128 KB, which is independent of underneath transportation protocols, i.e. your payload size is limited to 128KB bytes prior to Websocket framing, TLS encryption, and so on.

The maximum size of IP or TCP packets however varies. It depends on a few factors, including but not limited to network device MTU, TCP PMTU, payload size, and TLS cipher suites as well as encryption algorithms. I've found some related info online which might be useful for understanding the overhead TLS (again, the actual size may differ because of variaous factors like those mentioned above):
http://netsekure.org/2010/03/tls-overhead/
http://security.stackexchange.com/questions/58982/openssl-encrypting-small-packets-bandwidth-overhead

**Comment by fengsongAWS** [comment]
Close this issue since no response for a while.
