### ISSUE TITLE
sub directly from aws sdk js IOTData

### ISSUE THREAD

**Issue by nqd** [aws/aws-iot-device-sdk-js#91]
Hello, this is not directly with iot device sdk, but this is heavily related to IoT, then I guess this could be a place for the question.

I see that we can do pub from IOTData http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/IotData.html#publish-property. Just wondering why not provide api for sub?

**Comment by gkwicker** [comment]
Hi @nqd, that API is part of the [AWS SDK for JavaScript](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/) which uses HTTP REST API calls.  A subscribe call would not be possible in that context since the client and server do not have a persistent connection.  In order to provide the capability for clients to subscribe to updates, we need a long-lived connection between the client and the server.  [AWS IoT provides this with MQTT](http://docs.aws.amazon.com/iot/latest/developerguide/protocols.html), and [this SDK](https://github.com/aws/aws-iot-device-sdk-js) implements the client side of that connection for Node.js or browser environments.  For general questions about AWS services, the best place to go is the [AWS Developer Forums](https://forums.aws.amazon.com/index.jspa).  Thanks for using AWS IoT!
