### ISSUE TITLE
No Delta events raised after reconnect

### ISSUE THREAD

**Issue by mblackler** [aws/aws-iot-device-sdk-js#92]
I am currently testing what the behaviour is when the client has to go through a reconnection cycle when using shadow objects.

Delta events are firing fine after initially hooking everything up, but after forcing a reconnect (by switching off wifi on my Mac, then re-enabling wifi) delta events are no longer fired against a shadow update.  I make sure every time the connect event occurs, that the register call is being made to subscribe to updates on the shadow.

On the close event, the thingShadows object is unregistered from the original thingName.

Any thoughts on this issue?  Has this been seen before?  Is there something specific I should be doing after a reconnect?

**Comment by fengsongAWS** [comment]
Hi @mblackler,

The reconnection life cycle will resubscribe the shadow topics again when the network connection is back. You could monitor this by subscribing the life cycle events. 

I am not quite sure what do you mean by "close event". If you want to listen to shadow update, you have to make sure the thing shadow is not unregistered. Otherwise, even thought the connection is back, you cannot receive any shadow messages. 

Please feel free to let us know the details of your question so that we could repeat your problem. 

Thanks,
Fengyi

**Comment by fengsongAWS** [comment]
Close the issue for now and feel free to reopen it if you still have this problem.
